#!/bin/bash
set -e

# Initialize variables with default values
BUILD_TYPE="Release"
GPU=false

# Parse command-line options
while [[ $# -gt 0 ]]; do
	key="$1"
	case ${key} in
	-t | --build-type)
		BUILD_TYPE="$2"
		shift
		shift
		;;
	-g | --gpu)
		GPU=true
		echo "Requested GPU support."
		shift
		;;
	*)
		echo "Unknown option: $1"
		exit 1
		;;
	esac
done

# Set build directory and Spack environment based on GPU option
if ${GPU}; then
	BUILD_DIR="build_gpu"
	spack env activate aperi-mech-gpu
else
	BUILD_DIR="build"
	spack env activate aperi-mech
fi

# Create build directory
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}" || exit

# Remove CMakeCache if it exists
[[ -f CMakeCache.txt ]] && rm CMakeCache.txt

# Check for cmake in the spack environment, if not found, use the system cmake
if spack find -p cmake; then
	cmake=$(spack location -i cmake)/bin/cmake
else
	cmake=cmake
fi

# Configure CMake with specified build type and other options
cmake_command="${cmake}"

cmake_command+=" -D GPU:BOOL=${GPU}"
cmake_command+=" -D CMAKE_BUILD_TYPE:STRING=\"${BUILD_TYPE}\""
cmake_command+=" -D TRILINOS_PATH:FILEPATH=$(spack location -i trilinos)"
cmake_command+=" -D Kokkos_ROOT:FILEPATH=$(spack location -i kokkos)"
cmake_command+=" -D EIGEN_PATH:FILEPATH=$(spack location -i eigen)"
cmake_command+=" -D GTEST_PATH:FILEPATH=$(spack location -i googletest)"
cmake_command+=" -D OPENMPI_PATH:FILEPATH=$(spack location -i openmpi)"

# Add the cuda compiler to the cmake command
[[ ${GPU} == true ]] && cmake_command+=" -D CMAKE_CUDA_COMPILER:FILEPATH=$(spack location -i cuda)/bin/nvcc"

# Add the cuda flags to the cmake command. There has got to be a better way to do this. Needed?
[[ ${GPU} == true ]] && cmake_command+=" -D CMAKE_CUDA_FLAGS=\"-arch=sm_$(spack find kokkos | grep 'cuda_arch=' | awk -F'cuda_arch=' 'NR==1 {print $2}' | awk '{print $1}')\""

# Add the C++ compiler to the cmake command. There has got to be a better way to do this.
kokkos_compiler=$(spack find kokkos | grep -o 'kokkos%[^ ]*' | sed 's/kokkos%//')
kokkos_cxx_path=$(spack compiler info "${kokkos_compiler}" | grep 'cxx' | awk '{print $3}' | grep -v '^$')
cmake_command+=" -D CMAKE_CXX_COMPILER:FILEPATH=${kokkos_cxx_path}"

# Add the C compiler to the cmake command. Also, there has got to be a better way to do this.
kokkos_c_path=$(spack compiler info "${kokkos_compiler}" | grep 'cc' | awk '{print $3}' | grep -v '^$')
cmake_command+=" -D CMAKE_C_COMPILER:FILEPATH=${kokkos_c_path}"

# Add the C++ flags to the cmake command
cmake_command+=" -D CMAKE_CXX_FLAGS:STRING='-Wall -pedantic -Wno-long-long -ftrapv -Wno-deprecated'"

# Add the path to the stk_ngp_basic source code
cmake_command+=" .."

# Print and execute the cmake command
echo "CMake Command: ${cmake_command}"
eval "${cmake_command}"
